name:                haskell-to-js
version:             0.1.0.0
github:              "MurakamiKennzo/haskell-to-js"
license:             BSD3
author:              "murakami"
maintainer:          "w18191263056@yahoo.co.jp"
copyright:           "2021 murakami"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/MurakamiKennzo/haskell-to-js#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskell-to-js-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-to-js

tests:
  haskell-to-js-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-to-js
